<?php

/**
 * @file
 * Contains status_user.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function status_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the status_user module.
    case 'help.page.status_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module for create, update, delete status for user.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function status_interface_theme() {
  return array(
    'bg_url_formatter' => array(
      'variables' => array(
        'url' => NULL,
        'image_style' => NULL,
        'url_type' => NULL,
      ),
    ),
  );
}

/**
 * Prepares variables for `html.html.twig`.
 */
function status_interface_preprocess_html(&$variables) {
  // Check if current page is a node
  $node = \Drupal::routeMatch()->getParameter('node');
  // If is a node,
  // Check if is a vers content type, if is
  // process image field and put it to the body 
  if ($node instanceof \Drupal\node\NodeInterface) {
    if ($node->getType() === 'status_user') {
      if ($node->hasField('field_su_bg') && $node->field_su_bg->getValue() && $node->field_su_bg->getValue()[0]) {
        $variables['attributes']['class'][] = 'container-fluid-world';
        $file = $node->field_su_bg->referencedEntities()[0];
        if ($file->bundle() === 'image' && $file->hasField('field_media_image') && $file->field_media_image->getValue() && $file->field_media_image->getValue()[0]) {
          $image = $file->field_media_image->referencedEntities()[0];
          $image_uri = $image->getFileUri();
          $url = Url::fromUri(file_create_url($image_uri));
          $variables['attributes']['style'][] = 'background-image:url("'.$url->getUri().'");background-size:cover;background-repeat:no-repeat;min-height:600px;display:flex;align-items:center;justify-content:center;';
        }
      }else{
        $variables['attributes']['style'][] = 'min-height:600px;display:flex;align-items:center;justify-content:center;';
      }
    }
  }
}